const items = [

  {
    id: '001',
    item_image: './assets/images/cake/ricket-field-semi-fondant-birthday-cake.webp',
    item_name: 'Delicious Cricket Field Cake',
    current_price: 'Rs 999',
    original_price: `Rs 1999`,
    item_discount: '50',
  },

  {
    id: '002',
    item_image: './assets/images/cake/Anniversary Surprise Chocolate Pinata Ball Cake.webp',
    item_name: 'Chocolate Pinata Ball Cake',
    current_price: 'Rs 1499',
    original_price: `Rs 2999`,
    item_discount: '50',
  },

  {
    id: '003',
    item_image: './assets/images/cake/Decadent Dark Chocolate Cake.webp',
    item_name: 'Decadent Dark Chocolate Cake',
    current_price: 'Rs 999',
    original_price: `Rs 1999`,
    item_discount: '50',
  },

  {
    id: '004',
    item_image: './assets/images/cake/Lion Face Cake.webp',
    item_name: 'Delicious Lion Face Cake',
    current_price: 'Rs 999',
    original_price: `Rs 1999`,
    item_discount: '50',
  },

  {
    id: '005',
    item_image: './assets/images/cake/Tropical Fruit Cake.avif',
    item_name: 'Delightful  Delicious fruit Cake',
    current_price: 'Rs 1499',
    original_price: `Rs 2999`,
    item_discount: '50',
  },

  {
    id: '006',
    item_image: './assets/images/cake/black-and-white-teddy-bear-cake.webp',
    item_name: 'black & white teddy bear cake',
    current_price: 'Rs 999',
    original_price: `Rs 1999`,
    item_discount: '50',
  },

  {
    id: '007',
    item_image: './assets/images/cake/hazelnut-crunch-cake.webp',
    item_name: 'hazelnut - crunch  - cake',
    current_price: 'Rs 999',
    original_price: `Rs 1999`,
    item_discount: '50',
  },

  {
    id: '008',
    item_image: './assets/images/cake/jack-daniels-chocolate-cake.webp',
    item_name: 'jack daniels chocolate  cake',
    current_price: 'Rs 999',
    original_price: `Rs 1999`,
    item_discount: '50',
  },
  
  {
    id: '009',
    item_image: './assets/images/cake/Delicious Rasmalai Cake-2.webp',
    item_name: 'Delicious Rasmalai Cake',
    current_price: 'Rs 999',
    original_price: `Rs 1999`,
    item_discount: '50',
  },
  {
    id: '0010',
    item_image: './assets/images/chocolate/Bars choco chocolate.png',
    item_name: 'Bars choco chocolate',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '011',
    item_image: './assets/images/chocolate/Almond Candy.jpg',
    item_name: ' Almond Candy Chocolate',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '012',
    item_image: './assets/images/chocolate/Choco balls.png',
    item_name: 'Choco balls',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '013',
    item_image: './assets/images/chocolate/Choco Creme & Nut.jpg',
    item_name: 'Choco Creme & Nut Chocolate',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '014',
    item_image: './assets/images/chocolate/Chocolate Truffle.jpg',
    item_name: 'Chocolate Truffle',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '015',
    item_image: './assets/images/chocolate/chocolate-2.png',
    item_name: 'Chocolate-2',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '016',
    item_image: './assets/images/chocolate/chocolate-3.png',
    item_name: 'Chocolate-3',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '017',
    item_image: './assets/images/chocolate/chocolate-4.png',
    item_name: 'Chocolate-4',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '018',
    item_image: './assets/images/chocolate/chocolate-5.png',
    item_name: 'Chocolate-5',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '019',
    item_image: './assets/images/chocolate/chocolate.png',
    item_name: 'Chocolate-6',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '020',
    item_image: './assets/images/chocolate/Creme Brulle.jpg',
    item_name: 'Creme Brulle',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '021',
    item_image: './assets/images/chocolate/Praline with Plum.jpg',
    item_name: 'Praline with Pulum',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '022',
    item_image: './assets/images/chocolate/Praline with Nut.jpg',
    item_name: 'pineapple with nuts',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },


  {
    id: '023',
    item_image: './assets/images/cap-cake/Australia-Dark-Chocolate-cap-cake.webp',
    item_name: 'Cup-Cake-1',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '024',
    item_image: './assets/images/cap-cake/C.webp',
    item_name: 'Cup-cake-2',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },

  {
    id: '025',
    item_image: './assets/images/cap-cake/cap-cake-1.webp',
    item_name: 'Cup-cake-3',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '026',
    item_image: './assets/images/cap-cake/cap-cake-4.webp',
    item_name: 'Cup-cake-4',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },

  {
    id: '027',
    item_image: './assets/images/cap-cake/cap-cake-5.webp',
    item_name: 'Cup-cake-5',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
  {
    id: '028',
    item_image: './assets/images/cap-cake/Cup-cake-3.webp', //cap-cake-6
    item_name: 'Cup-cake-6',
    current_price: 'Rs ',
    original_price: `Rs `,
    item_discount: '50',
  },
 

];